# Javascript Node CircleCI 2.0 configuration file

defaults: &defaults
  docker:
    - image: circleci/openjdk:8u171-jdk-node-browsers
    - image: circleci/mongo:4.2

  working_directory: ~/agile-todo

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          name: Restore backend/general packages
          keys:
            - v1-dependencies-{{.Branch}}-{{ checksum "package.json" }}
            - v1-dependencies-{{.Branch}}-
            - v1-dependencies-

      - run:
          name: Install backend and general dependencies
          command: npm install

      - save_cache:
          name: Save backend/general packages cache
          paths:
            - ~/.cache/node_modules
          key: v1-dependencies-{{.Branch}}-{{ checksum "package.json" }}

      - restore_cache:
          name: Restore frontend packages
          keys:
            - v1-dependencies-{{.Branch}}-{{ checksum "client/package.json" }}
            - v1-dependencies-{{.Branch}}-
            - v1-dependencies-

      - run:
          name: Install frontend packages
          command: cd client && npm install

      - save_cache:
          paths:
            - ~/.cache/node_modules
            - ~/client/.cache/node_modules
          key: v1-dependencies-{{.Branch}}-{{ checksum "client/package.json" }}

      - run:
          name: Build frontend react app
          command: cd client && npm run build

      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - agile-todo
      #       - .cache

workflows:
  version: 2
  starter-workflow:
    jobs:
      - build
